version: '3'

services:
  app:
    image: cluster-api
    environment:
      - MIX_ENV=dev
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8000:8000"