version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/app
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8000:8000"