version: '3.7'

services:
  cluster:
    image: "cluster:latest"
    deploy:
      replicas: 2
    healthcheck:
      test: curl -f http://localhost:4000/api/ready || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8000:8000"
    deploy:
      #mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]